[2023-08-31 13:23:07,829] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2021-12-08T00:00:00+00:00 [queued]>
[2023-08-31 13:23:07,902] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2021-12-08T00:00:00+00:00 [queued]>
[2023-08-31 13:23:07,903] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-08-31 13:23:07,904] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-08-31 13:23:07,904] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-08-31 13:23:07,966] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2021-12-08T00:00:00+00:00
[2023-08-31 13:23:07,979] {standard_task_runner.py:52} INFO - Started process 4675 to run task
[2023-08-31 13:23:08,002] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v5', 'second_task', '2021-12-08T00:00:00+00:00', '--job-id', '403', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmph6hiiy82', '--error-file', '/tmp/tmpep_0j2qd']
[2023-08-31 13:23:08,019] {standard_task_runner.py:77} INFO - Job 403: Subtask second_task
[2023-08-31 13:23:08,266] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v5.second_task 2021-12-08T00:00:00+00:00 [running]> on host e7718740c1e6
[2023-08-31 13:23:08,463] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=devendra
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-12-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-08T00:00:00+00:00
[2023-08-31 13:23:08,466] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-08-31 13:23:08,471] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2023-08-31 13:23:08,489] {bash.py:169} INFO - Output:
[2023-08-31 13:23:08,545] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2023-08-31 13:23:08,558] {bash.py:177} INFO - Command exited with return code 0
[2023-08-31 13:23:08,624] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20211208T000000, start_date=20230831T132307, end_date=20230831T132308
[2023-08-31 13:23:08,770] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-31 13:23:08,814] {local_task_job.py:146} INFO - Task exited with return code 0
